# Generated by Django 3.1.5 on 2021-01-19 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightApp', '0002_auto_20210118_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='departureCity',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
